[package]
name = "zed_edge"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
path = "src/edge.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.1.0"
