id = "edge"
name = "Edge"
version = "0.2.0"
schema_version = 1
authors = ["Abdelmadjid Cherfaoui <contact@hexacker.com>"]
description = "Add Syntax Highlight Support for EdgeJS"
repository = "https://github.com/Hexacker/zed-edge.git"

[grammars.edge]
repository = "https://github.com/Hexacker/tree-sitter-edge"
rev = "a53d25ad1fae73fab97bbbd78fb5548ac29045c6"
