id = "edge"
name = "Edge"
version = "1.0.1"
schema_version = 1
authors = ["Abdelmadjid Cherfaoui <contact@hexacker.com>"]
description = "Edge template language support with syntax highlighting and language server integration"
repository = "https://github.com/Hexacker/zed-edge.git"

[grammars.edge]
repository = "https://github.com/Hexacker/tree-sitter-edge"
rev = "e18511cbab58d115484b321b1e6afcfa19023ffc"

[language_servers.edge-language-server]
name = "edge-language-server"
language = "Edge"
